version: '3.8'
services:
  redis:
    image: redis
    container_name: cache
    networks:
      - my-network
    ports:
      - "6379:6379"

  backend:
    image: url-shortner
    container_name: url-shortener-service
    networks:
      - my-network
    environment:
      - REDIS_HOST=my-redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000

networks:
  my-network:
    driver: bridge
